/**
 * PrintFolio v0.1.2
 * Responsibility: Connect file loading, parsing, thumbnail rendering, tabs,
 * material-cost tracking, and future reprint-planning placeholders.
 */
(function(){
  "use strict";
  const $=id=>document.getElementById(id),state={parsed:null},file=$("file"),canvas=$("canvas");
  const esc=v=>String(v??"—").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;"),dash=v=>v===null||v===undefined||v===""?"—":v;
  const mm=v=>Number.isFinite(v)?v.toFixed(2)+" mm":"—",temp=v=>Number.isFinite(v)?v.toFixed(0)+" °C":"—",speed=v=>Number.isFinite(v)?(v/60).toFixed(1)+" mm/s":"—",meters=v=>Number.isFinite(v)?v.toFixed(2)+" m":"—",grams=v=>Number.isFinite(v)?v.toFixed(2)+" g":"—";
  function table(title,rows){return `<div class="metric"><h3>${esc(title)}</h3><table><tbody>${rows.map(r=>`<tr><th>${esc(r[0])}</th><td>${esc(dash(r[1]))}</td></tr>`).join("")}</tbody></table></div>`}
  function materialLibrary(){try{return JSON.parse(localStorage.getItem("printfolio.materials")||"[]")}catch(_){return[]}}
  function saveMaterials(v){localStorage.setItem("printfolio.materials",JSON.stringify(v))}
  function materialCost(p,m){if(!m||!Number.isFinite(p.filamentGrams)||!Number.isFinite(m.totalWeight)||m.totalWeight<=0||!Number.isFinite(m.totalCost))return null;return p.filamentGrams/m.totalWeight*m.totalCost}
  function renderMaterials(){const list=materialLibrary(),sel=$("materialSelect");sel.innerHTML=`<option value="">Select material…</option>`+list.map((m,i)=>`<option value="${i}">${esc(m.name)}${m.color?" — "+esc(m.color):""}</option>`).join("");$("materialList").innerHTML=list.length?list.map((m,i)=>`<tr><td>${esc(m.name)}</td><td>${esc(m.color||"—")}</td><td>${esc(m.purchased||"—")}</td><td>${esc(m.opened||"—")}</td><td>${Number(m.totalWeight||0).toFixed(0)} g</td><td>$${Number(m.totalCost||0).toFixed(2)}</td><td><button class="small danger" data-remove="${i}">Remove</button></td></tr>`).join(""): `<tr><td colspan="7" class="note">No materials saved yet. Materials are stored only in this browser.</td></tr>`;updateCost()}
  function updateCost(){const p=state.parsed,idx=$("materialSelect")?.value,list=materialLibrary(),m=idx!==""?list[Number(idx)]:null;$("costResult").textContent=p&&m?((materialCost(p,m)!==null)?`Estimated material cost: $${materialCost(p,m).toFixed(2)}`:"Estimated material cost requires filament weight in the print file."):"Select a material to estimate print cost."}
  function update(p){
    $("basic").innerHTML=[["Print",p.fileName],["File Type",p.fileType],["Printer",p.printer],["Slicer",p.slicer],["Source Model",p.sourceModel],["Material",p.materialType],["Print Time",p.printTimeDisplay],["Filament",p.filamentMeters!==null?meters(p.filamentMeters):grams(p.filamentGrams)]].map(r=>`<div><dt>${esc(r[0])}</dt><dd>${esc(dash(r[1]))}</dd></div>`).join("");
    const zNote=p.dimensionNotes?.length?p.dimensionNotes.join(" "):null;
    $("dimensionsContent").innerHTML=table("Overall Size",[["X",mm(p.dimensionSize.x)],["Y",mm(p.dimensionSize.y)],["Z",mm(p.dimensionSize.z!==null?p.dimensionSize.z:p.maxLayerZ)],["Layer Height",mm(p.layerHeight)],["Layers",p.layerCount||"—"]])+(zNote?`<div class="metric noteBox"><b>Dimension note</b><p>${esc(zNote)}</p></div>`:"")+table("Bounding Box",[["X Minimum",mm(p.bounds.minX)],["X Maximum",mm(p.bounds.maxX)],["Y Minimum",mm(p.bounds.minY)],["Y Maximum",mm(p.bounds.maxY)],["Z Minimum",mm(p.bounds.minZ)],["Z Maximum",mm(p.bounds.maxZ)]]);
    $("temperaturesContent").innerHTML=table("Nozzle",[["Initial / warm-up",temp(p.initialNozzleTemperature)],["Print temperature",temp(p.nozzleTemperature)]])+table("Build Plate",[["Initial / first layer",temp(p.initialBedTemperature)],["Print temperature",temp(p.bedTemperature)]]);
    $("speedsContent").innerHTML=table("Configured Speeds",[["Print speed",Number.isFinite(p.printSpeed)?speed(p.printSpeed):"—"],["Travel speed",Number.isFinite(p.travelSpeed)?speed(p.travelSpeed):"—"],["Minimum G-code feed rate",speed(p.movement.minFeedRate)],["Maximum G-code feed rate",speed(p.movement.maxFeedRate)]])+table("Movement Summary",[["Extrusion moves",p.movement.extrusionMoves.toLocaleString()],["Travel moves",p.movement.travelMoves.toLocaleString()]]);
    $("filamentContent").innerHTML=table("Filament",[["Reported length",meters(p.filamentMeters)],["Reported weight",grams(p.filamentGrams)],["Reported volume",p.filamentCm3!==null?p.filamentCm3.toFixed(2)+" cm³":"—"],["File-reported filament cost",p.filamentCost!==null?"$"+p.filamentCost.toFixed(2):"—"],["Extrusion mode",p.extrusionMode],["Retractions",p.movement.retractions.toLocaleString()]])+table("Scope",[["Purpose","Preview and inspection only"],["Slicing","Not performed by PrintFolio"]]);
    $("coolingContent").innerHTML=table("Fan Cooling",[["Cooling commands detected",p.coolingDetected?"Yes":"No"],["Maximum fan command",p.fanMax===null?"—":p.fanMax+" / 255"]])+table("File",[["G-code flavor",p.gcodeFlavor],["Thumbnail source",p.thumbnailSource||"PrintFolio renderer"]]);
    $("bedsetupContent").innerHTML=table("Bed / Leveling",[["Homing detected",p.bedSetup.homing?"Yes":"Not detected"],["Mesh probing detected",p.bedSetup.meshProbe?"Yes":"Not detected"],["Mesh load detected",p.bedSetup.meshLoad?"Yes":"Not detected"],["Leveling commands",p.bedSetup.meshCommands.length?p.bedSetup.meshCommands.join(", "):"—"],["Bed shape",p.bedSetup.bedShape]])+table("Printer Setup",[["Printer",p.printer],["Nozzle diameter",p.bedSetup.nozzleDiameter!==null?p.bedSetup.nozzleDiameter+" mm":"—"],["Filament diameter",p.bedSetup.filamentDiameter!==null?p.bedSetup.filamentDiameter+" mm":"—"],["Extruder count",p.bedSetup.extruderCount]]);
    $("settingsContent").innerHTML=table("Supports & Infill",[["Supports",p.printSettings.support],["Support build plate only",p.printSettings.supportBuildplateOnly],["Infill density",p.printSettings.infillDensity],["Infill pattern",p.printSettings.infillPattern]])+table("Shell & Adhesion",[["Wall / perimeter lines",p.printSettings.wallLines],["Top layers",p.printSettings.topLayers],["Bottom layers",p.printSettings.bottomLayers],["Brim width",p.printSettings.brimWidth!==null?p.printSettings.brimWidth+" mm":null],["Raft",p.printSettings.raft],["Skirt lines / height",p.printSettings.skirtLines],["Ironing",p.printSettings.ironing],["Adhesion",p.printSettings.adhesion]])+`<div class="metric future"><h3>Future: Reprint Planning</h3><p>PrintFolio will eventually let you create a new print plan from this file—changing material, temperature, speed, fan cooling, supports, infill, and other settings while preserving the original print record.</p><p class="note">v0.1.x is intentionally read-only.</p></div>`;
    $("materialFileSummary").innerHTML=table("Current Print",[["Material in file",p.materialType],["Color in file",p.materialColor],["Filament used",p.filamentGrams!==null?grams(p.filamentGrams):meters(p.filamentMeters)],["Cost from file",p.filamentCost!==null?"$"+p.filamentCost.toFixed(2):"Not reported"]]);renderMaterials();
  }
  function empty(){const html='<div class="emptyPanel">Open a G-code, BGCODE, or 3MF file to populate this section.</div>';["dimensionsContent","temperaturesContent","speedsContent","filamentContent","coolingContent","bedsetupContent","settingsContent","materialFileSummary"].forEach(id=>$(id).innerHTML=html);renderMaterials()}
  function clear(){state.parsed=null;const c=canvas.getContext("2d");c.clearRect(0,0,canvas.width,canvas.height);c.fillStyle="#edf2f4";c.fillRect(0,0,canvas.width,canvas.height);$("empty").hidden=false;$("fileLabel").textContent="No file loaded";$("previewFile").textContent="No file loaded.";$("status").textContent="Open a G-code, BGCODE, or 3MF file to begin.";$("basic").innerHTML=[["Print","—"],["File Type","—"],["Printer","—"],["Slicer","—"],["Source Model","—"],["Material","—"],["Print Time","—"],["Filament","—"]].map(r=>`<div><dt>${r[0]}</dt><dd>${r[1]}</dd></div>`).join("");empty()}
  file.addEventListener("change",()=>{const f=file.files?.[0];if(!f)return;$("status").textContent="Reading "+f.name+"…";const r=new FileReader();r.onload=async e=>{try{const p=await GCodeParser.parseBytes(new Uint8Array(e.target.result),f.name);state.parsed=p;GCodeRenderer.renderThumbnail(canvas,p);$("empty").hidden=true;$("fileLabel").textContent=f.name;$("previewFile").textContent=f.name;update(p);const extra=p.fileType==="BGCODE"?" • embedded metadata read":p.fileType==="3MF"?" • project metadata/model read":"";$("status").textContent=`Loaded ${f.name} • ${p.fileType}${extra}.`;}catch(err){console.error(err);$("status").textContent="Could not parse the file: "+err.message}};r.onerror=()=>$("status").textContent="The file could not be read.";r.readAsArrayBuffer(f)});
  $("clear").addEventListener("click",()=>{file.value="";clear()});
  document.querySelectorAll(".tab").forEach(t=>t.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===t));document.querySelectorAll(".panel").forEach(x=>{const on=x.id===t.dataset.tab;x.hidden=!on;x.classList.toggle("active",on)})}));
  $("materialSelect").addEventListener("change",updateCost);
  $("materialForm").addEventListener("submit",e=>{e.preventDefault();const m={name:$("matName").value.trim(),color:$("matColor").value.trim(),purchased:$("matPurchased").value,opened:$("matOpened").value,totalWeight:Number($("matWeight").value),totalCost:Number($("matCost").value)};if(!m.name)return;const list=materialLibrary();list.push(m);saveMaterials(list);e.target.reset();renderMaterials()});
  $("materialList").addEventListener("click",e=>{const i=e.target.dataset.remove;if(i===undefined)return;const list=materialLibrary();list.splice(Number(i),1);saveMaterials(list);renderMaterials()});
  clear();
})();
